#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

# Temporal restart command

temporal:restart() {
    local service_name="$1"
    
    if ! validate_service_name "$service_name" "restart"; then
        return 1
    fi

    temporal:stop "$service_name"
    temporal:start "$service_name"
}
