#!/usr/bin/env bash

# Source plugin helpers
. "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

# Plugin name
PLUGIN_COMMAND_PREFIX="temporal"
PLUGIN_SERVICE="temporal"

# Plugin paths
PLUGIN_CONFIG_ROOT="$DOKKU_LIB_ROOT/config/temporal"

# Set PLUGIN_DATA_ROOT - this is the canonical location for service data
export TEMPORAL_ROOT=${TEMPORAL_ROOT:="$DOKKU_LIB_ROOT/services/temporal"}
export PLUGIN_DATA_ROOT=$TEMPORAL_ROOT

# Plugin version
PLUGIN_VERSION="$(cat "$PLUGIN_PATH/VERSION")"
